export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const CART_SAVE_SHIPPING_ADDRESS = "CART_SAVE_SHIPPING_ADDRESS"

export const SET_PAYMENT = "SET_PAYMENT"